branch-defaults:
  master:
    environment: prod-env
    group_suffix: null
global:
  application_name: quiz_tool
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Multi-container Docker 17.09.1-ce (Generic)
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
